### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by new-username** [vorlovsky/Tesseract-OCR-ANE#1]
Hello,

I came across your ane and thought to test it out on a Samsung Galaxy S3, however it crashes without any notice. The output that I receive is as follows....

```
RecognizeCommand
eng
1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
f9e0ba40-d621-41c3-9c75-4c2564232357
start recognition
bitmap 400 23
TessBaseAPI created
Debug session terminated.
```

Do you have any ideas why this crash occurs?

Many Thanks :)

**Comment by vorlovsky** [comment]
Hi!

First of all, let's check if trained data files are referenced correctly.
Can you, please, 1) show ANE initialization in your AS3 code and 2) specify full path to tessdata folder on your S3 phone?

**Comment by new-username** [comment]
Thanks for getting back to me.

The code is very basic, simply getting the image from the library (which displays on stage) and when stage is clicked passing the bitmapData.

```
import flash.filesystem.File;
import com.lj.ane.tesseract.TesseractANE;
import com.lj.ane.tesseract.events.TesseractANEEvent;

var _ane;

var bitmapData:BitmapData = new image1();
var bitmap:Bitmap = new Bitmap(bitmapData);
addChildAt(bitmap,0);

stage.addEventListener(MouseEvent.CLICK, init);
function init(e:MouseEvent):void
{
	txt.text = "started";
	try
	{
		_ane = TesseractANE.getInstance();
		_ane.absoluteTessdataPath = File.applicationDirectory.nativePath;
		_ane.language = "eng";
		
		_ane.addEventListener(TesseractANEEvent.RECOGNIZED, onTextRecognized);
		
		var uuid:String = _ane.recognize(bitmapData);
	}
	catch (e:Error)
	{
		txt.text = e.toString();
	}
}

function onTextRecognized(event:TesseractANEEvent):void
{
   	txt.text = "end recoignizing " + event.uuid + " > " + event.text;
}
```

The tessdata is being packaged with the apk (assets\tessdata\eng.traineddata) which is the reasoning I used File.applicationDirectory.nativePath as the path. Documentation showed not to include "tessdata/" within the path.

**Comment by vorlovsky** [comment]
According to http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/File.html "the nativePath property of a File object pointing to the application directory is an empty string".
I think that's the reason, cause you need to provide a full path.

**Comment by new-username** [comment]
Oh I missed that, thanks!

I tried using the url property which returns "app:" however this causes a crash too. After checking an absolute path from the sd card storage it worked so clearly a path issue.

Do you know of any way to reference the application path? Or am I forced to download the tessdata to the storage directory?

**Comment by new-username** [comment]
After trying to manually input the app path "/data/data/air.applicationID/", I read that the files in the assets directory don't get unpacked so of course the path wouldn't be referenced. The workaround seems to be to copy the asset into the storage directory then reference that path instead.

The only other problem with referencing the storage directory, is that as pointed out earlier nativePath returns an empty string and url would return "app-storage:/". A a manual input of "/data/data/air.applicationID/filename/Local Store/" should work in this case. I have yet to test this out though.

**Comment by vorlovsky** [comment]
> The only other problem with referencing the storage directory, is that as pointed out earlier nativePath returns an empty string

I've not checked myself if it's true, but there is no such statement in the AS3 reference for applicationStorageDirectory.nativePath (unlike for the applicationDirectory.nativePath).

There is a short code sample from my test project for iOS, probably it will work on Android too:

    var externalTessdata : File = File.applicationStorageDirectory.resolvePath("tessdata");
			
    if(!externalTessdata.exists) {				
	    var tessdata : File = File.applicationDirectory.resolvePath("tessdata");	
	    tessdata.copyTo(externalTessdata, true);
    }
			
    _ane.absoluteTessdataPath = File.applicationStorageDirectory.nativePath;

Anyway, you should use some hardcoded path or a 'nativePath', not an 'url', because the lib will NOT accept any pseudo protocols (app://, etc.).

**Comment by new-username** [comment]
You're right, I was being tired and lazy assuming nativePath would return empty for the storage directory without looking into the documentation.

Thanks for the snippet! I was thinking to do something similar however using copyToAsync instead. The ane worked fine with File.applicationStorageDirectory.nativePath after the copy.

In regards to hardcoding the path, I was trying to avoid this for cross platform situations. I know url doesn't provide the absolute path but just covering my bases. At least now I know understand why File.applicationDirectory.nativePath returns empty.

Thanks for all your help, much appreciated.

**Comment by vorlovsky** [comment]
You are welcome.
